import { useMemo, useState } from 'react';
import { FlightScene } from './Scene';
import { GEOMETRY_LIBRARY, computeGeometry, type GeometryFamily, type GeometryState, type ShapeId } from './geometry';
import { analyticalAirfoilCoefficients, calculatePhysics } from './physicsEngine';

const defaults: Record<string, number> = { chord: 1, span: 6, radius: 1, length: 2, width: 1, height: 1, base: 1, semiMajor: 1, semiMinor: 0.6, side: 1, radius1: 1, radius2: 0.6, radiusX: 1, radiusY: 0.8, radiusZ: 0.6 };
const families: { id: GeometryFamily; label: string }[] = [{ id: 'airfoil', label: 'AIRFOILS / WINGS' }, { id: 'shape2d', label: '2D SHAPES' }, { id: 'solid3d', label: '3D SOLIDS' }];
const fmt = (value: number, digits = 2) => new Intl.NumberFormat('en-IN', { maximumFractionDigits: digits }).format(value);
function getDefaultState(id: ShapeId): GeometryState { const def = GEOMETRY_LIBRARY.find((item) => item.id === id)!; return { id, flowMode: 'axis', values: Object.fromEntries(def.parameters.map((key) => [key, defaults[key] ?? 1])) }; }

export default function App() {
  const [geometry, setGeometry] = useState<GeometryState>(getDefaultState('naca2412')); const [family, setFamily] = useState<GeometryFamily>('airfoil');
  const [velocity, setVelocity] = useState(62); const [density, setDensity] = useState(1.225); const [viscosity, setViscosity] = useState(1.81e-5); const [alpha, setAlpha] = useState(5); const [mass, setMass] = useState(1200); const [efficiency, setEfficiency] = useState(0.82);
  const [windDirection, setWindDirection] = useState<'leftToRight' | 'rightToLeft'>('leftToRight'); const [source, setSource] = useState<'analytical' | 'measured'>('analytical'); const [manualCl, setManualCl] = useState(0.5); const [manualCd, setManualCd] = useState(0.04); const [activeTab, setActiveTab] = useState('flight');
  const geometryDef = useMemo(() => GEOMETRY_LIBRARY.find((item) => item.id === geometry.id)!, [geometry.id]); const activeFamily = geometryDef.family;
  const geo = useMemo(() => computeGeometry(geometry), [geometry]);
  const coefficients = useMemo(() => { if (source === 'measured') return { cl: manualCl, cd: manualCd, clMax: 1.4 }; if (activeFamily === 'airfoil') return analyticalAirfoilCoefficients(alpha, geo.aspectRatio, efficiency); const cdMap: Partial<Record<ShapeId, number>> = { cube: 1.05, cuboid: 1, rectangularPrism: 1, sphere: 0.47, cylinder: 0.82, cone: 0.5, triangularPrism: 1, squarePyramid: 0.8, coneFrustum: 0.7, ellipsoid: 0.2, circle: 0.1, rectangle: 1, triangle: 1, ellipse: 0.15 }; return { cl: 0, cd: cdMap[geometry.id] ?? 1, clMax: 1.4 }; }, [source, manualCl, manualCd, activeFamily, geometry.id, alpha, geo.aspectRatio, efficiency]);
  const physics = useMemo(() => calculatePhysics({ densityKgM3: density, velocityMs: velocity, referenceAreaM2: geo.referenceAreaM2, characteristicLengthM: geo.characteristicLengthM, aspectRatio: geo.aspectRatio, viscosityPaS: viscosity, angleOfAttackDeg: alpha, massKg: mass, cl: coefficients.cl, cd: coefficients.cd, clMax: coefficients.clMax, oswaldEfficiency: efficiency, speedOfSoundMs: 340.3, coefficientSource: source, isLiftingSurface: activeFamily === 'airfoil' }), [density, velocity, geo, viscosity, alpha, mass, coefficients, efficiency, source, activeFamily]);
  const selectShape = (id: ShapeId) => { setGeometry(getDefaultState(id)); setActiveTab('geometry'); }; const updateParameter = (key: string, value: number) => setGeometry((prev) => ({ ...prev, values: { ...prev.values, [key]: value } })); const scrollTo = (tab: string) => { setActiveTab(tab); document.getElementById(tab)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };

  return <main className="app-shell">
    <header className="topbar"><div><div className="brand">AIRCRAFT FLIGHT LAB</div><div className="subtitle">Interactive aerospace engineering learning tool</div></div><nav>{[['flight','FLIGHT LAB'],['geometry','GEOMETRY'],['performance','PERFORMANCE'],['stall','STALL ANALYSIS'],['about','ABOUT / VALIDATION']].map(([id,label]) => <button className={activeTab === id ? 'tab active' : 'tab'} key={id} onClick={() => scrollTo(id)}>{label}</button>)}</nav></header>
    <section id="flight" className="workspace">
      <aside className="panel left-panel"><h2>GEOMETRY LIBRARY</h2><p className="muted">Select a family, then select a mathematically defined shape.</p><div className="family-grid">{families.map((item) => <button key={item.id} className={family === item.id ? 'choice selected' : 'choice'} onClick={() => setFamily(item.id)}>{item.label}</button>)}</div><div className="shape-grid">{GEOMETRY_LIBRARY.filter((item) => item.family === family).map((item) => <button key={item.id} className={geometry.id === item.id ? 'choice selected' : 'choice'} onClick={() => selectShape(item.id)}>{item.name}</button>)}</div><div id="geometry" className="section-anchor" /><h2>PARAMETER GENERATOR</h2><p className="muted">Every dimension drives both the renderer and geometry calculation.</p>{geometryDef.parameters.map((key) => <label className="field" key={key}><span>{key}</span><input type="number" min="0.001" step="any" value={geometry.values[key]} onChange={(e) => updateParameter(key, Number(e.target.value))}/><small>m</small></label>)}{activeFamily === 'solid3d' && <div className="segmented"><button className={geometry.flowMode === 'axis' ? 'selected' : ''} onClick={() => setGeometry((g) => ({ ...g, flowMode: 'axis' }))}>AXIS / FLOW</button><button className={geometry.flowMode === 'face' ? 'selected' : ''} onClick={() => setGeometry((g) => ({ ...g, flowMode: 'face' }))}>FACE / FLOW</button></div>}<div className="metric-grid"><div><small>REFERENCE AREA</small><strong>{fmt(geo.referenceAreaM2,4)} m²</strong></div><div><small>VOLUME</small><strong>{fmt(geo.volumeM3,4)} m³</strong></div><div><small>ASPECT RATIO</small><strong>{fmt(geo.aspectRatio,3)}</strong></div><div><small>FORMULA</small><strong className="formula">{geo.formula}</strong></div></div></aside>
      <section className="stage"><div className="stage-label"><strong>FLOW VISUALIZATION</strong><span>QUALITATIVE ENGINEERING MODEL</span></div><FlightScene geometry={geometry} angleDeg={activeFamily === 'airfoil' ? alpha : 0} windDirection={windDirection}/><div className="wind-badge">Wind → object → boundary layer → separation / wake</div></section>
      <aside className="panel right-panel"><h2>LIVE TELEMETRY</h2><p className="muted">All values recompute from the deterministic model.</p>{[['Dynamic pressure q', `${fmt(physics.dynamicPressurePa,1)} Pa`],['Lift L', `${fmt(physics.liftN,1)} N`],['Drag D', `${fmt(physics.dragN,1)} N`],['L / D', fmt(physics.liftToDrag,2)],['Cᴸ', coefficients.cl.toFixed(4)],['Cᴰ', coefficients.cd.toFixed(4)],['Reynolds', physics.reynolds.toExponential(2)],['Mach', physics.mach.toFixed(3)]].map(([label,value], i) => <div className="telemetry" key={label}><span>{label}</span><strong className={i === 1 ? 'green' : i === 2 ? 'red' : ''}>{value}</strong></div>)}<div className="control-group"><h3>AERODYNAMIC CONDITIONS</h3><Range label="Airspeed V" value={velocity} min={0} max={200} step={1} unit="m/s" onChange={setVelocity}/><Range label="Air density ρ" value={density} min={0.1} max={2} step={0.001} unit="kg/m³" onChange={setDensity}/><Range label="Dynamic viscosity μ" value={viscosity} min={0.00001} max={0.00003} step={0.000001} unit="Pa·s" onChange={setViscosity}/><Range label="Angle of attack α" value={alpha} min={-20} max={30} step={0.5} unit="deg" onChange={setAlpha}/><Range label="Aircraft mass" value={mass} min={0} max={50000} step={10} unit="kg" onChange={setMass}/><Range label="Oswald efficiency e" value={efficiency} min={0.55} max={1} step={0.01} unit="" onChange={setEfficiency}/></div><div className="segmented"><button className={source === 'analytical' ? 'selected' : ''} onClick={() => setSource('analytical')}>ANALYTICAL</button><button className={source === 'measured' ? 'selected' : ''} onClick={() => setSource('measured')}>MEASURED</button></div>{source === 'measured' && <div className="manual-coeff"><label className="field"><span>CL</span><input type="number" step="0.01" value={manualCl} onChange={(e) => setManualCl(Number(e.target.value))}/></label><label className="field"><span>CD</span><input type="number" step="0.001" value={manualCd} onChange={(e) => setManualCd(Number(e.target.value))}/></label></div>}<div className="segmented"><button className={windDirection === 'leftToRight' ? 'selected' : ''} onClick={() => setWindDirection('leftToRight')}>← LEFT → RIGHT</button><button className={windDirection === 'rightToLeft' ? 'selected' : ''} onClick={() => setWindDirection('rightToLeft')}>RIGHT → LEFT</button></div></aside>
    </section>
    <section id="performance" className="content-section"><h2>PERFORMANCE</h2><div className="result-grid"><Result title="Lift" value={`${fmt(physics.liftN,1)} N`} detail="L = qSCᴸ"/><Result title="Drag" value={`${fmt(physics.dragN,1)} N`} detail="D = qSCᴰ"/><Result title="L / D" value={fmt(physics.liftToDrag,2)} detail="Aerodynamic efficiency"/><Result title="Weight" value={`${fmt(physics.weightN,1)} N`} detail="W = mg"/></div><p className="explanation">The performance panel uses the same reference area and coefficients as telemetry.</p></section>
    <section id="stall" className="content-section"><h2>STALL / SEPARATION</h2>{activeFamily === 'airfoil' ? <div className="result-grid"><Result title="Estimated stall speed" value={`${fmt(physics.stallSpeedMs ?? 0,1)} m/s`} detail="Vs = √(2W / ρSCLmax)"/><Result title="AoA margin" value={`${fmt(physics.stallMarginDeg ?? 0,1)}°`} detail="Educational estimate relative to 15°"/><Result title="Separation estimate" value={`${fmt((physics.separationEstimate ?? 0) * 100,0)}%`} detail="Qualitative model, not CFD"/></div> : <p className="warning">Stall is a lifting-surface concept. Bluff bodies report drag and wake behaviour instead.</p>}</section>
    <section id="about" className="content-section"><h2>ABOUT / VALIDATION</h2><div className="validation"><p><strong>Accuracy definition:</strong> exact arithmetic is claimed only for implemented mathematical formulas. CL, CD, stall, separation and wake are engineering models/estimates unless supplied from measured data or validated aerodynamic data.</p><p><strong>Pipeline:</strong> Geometry Library → Parameter Generator → Exact Geometry Engine → Aerodynamic Reference Area → Physics Engine → 3D Visualization → Performance → Stall → Engineering Explanation → Validation.</p><p><strong>Student safeguard:</strong> every result is tied to visible inputs, equations and an explicit model label.</p></div></section>
  </main>;
}
function Range({ label, value, min, max, step, unit, onChange }: { label: string; value: number; min: number; max: number; step: number; unit: string; onChange: (v:number)=>void }) { return <label className="range"><span>{label}<strong>{Number.isInteger(step) ? value : value.toFixed(6)} {unit}</strong></span><input type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))}/></label>; }
function Result({ title, value, detail }: { title:string; value:string; detail:string }) { return <div className="result"><span>{title}</span><strong>{value}</strong><small>{detail}</small></div>; }
